version: "3.8"

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: bidon
    volumes:
      - database-content:/var/lib/postgresql/data
    expose:
      - 5432

  adminer:
    image: adminer
    ports:
      - 8090:8080

volumes:
  database-content: